package jdbc;

import java.awt.Color;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.event.ChangeEvent;


public class DatabaseGUI extends javax.swing.JFrame {

    /**
     * Creates new form databaseGUI
     */
    public DatabaseGUI() {
        initComponents();
        
        tabs = new TreeMap<Integer, TabInfo>();
        for (int i = 0; i < tabbedPane.getTabCount(); ++i) {
            tabs.put(i, new TabInfo(tabbedPane.getTitleAt(i)));
        }
        
        dbActions = new DBActions(this);
        
        tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            // tab in the TabbedPane changed
            @Override
            public void stateChanged(ChangeEvent e) {
                int i = ((javax.swing.JTabbedPane)e.getSource()).getSelectedIndex();
                TabInfo tab = tabs.get(i);
                if (!tab.initialized) {
                    if (tab.tabName.equalsIgnoreCase("workshops")) { //TEMP
                    try {
                        javax.swing.table.TableModel tableModel = DatabaseTableModel.createTableModelForDBTable(tab.tabName);
                        workshopsTable.setModel(tableModel);
                        tab.initialized = true;
                    } catch (java.sql.SQLException ex) {
                        setErrorMessage("workshops", ex.getLocalizedMessage());
                    }
                    //tab.initialized = true;
                }}
            }       
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        caseweekPanel = new javax.swing.JPanel();
        workshopsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workshopsTable = new javax.swing.JTable();
        workshopLabel = new javax.swing.JLabel();
        workshopNameField = new javax.swing.JTextField();
        workshopAddButton = new javax.swing.JButton();
        workshopRoomTypeCombo = new javax.swing.JComboBox<>();
        workshopDateField = new javax.swing.JTextField();
        workshopNameLabel = new javax.swing.JLabel();
        workshopDateLabel = new javax.swing.JLabel();
        workshopRoomTypeLabel = new javax.swing.JLabel();
        workshopOrganizerLabel = new javax.swing.JLabel();
        workshopOrganizerField = new javax.swing.JTextField();
        workshopGroupQtyLabel = new javax.swing.JLabel();
        workshopRoomSettingLabel = new javax.swing.JLabel();
        workshopGroupQtyField = new javax.swing.JTextField();
        workshopRoomSettingCombo = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        errorMessageLabel = new javax.swing.JLabel();
        speakersPanel = new javax.swing.JPanel();
        studentsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CaseWeekDB");

        tabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout caseweekPanelLayout = new javax.swing.GroupLayout(caseweekPanel);
        caseweekPanel.setLayout(caseweekPanelLayout);
        caseweekPanelLayout.setHorizontalGroup(
            caseweekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        caseweekPanelLayout.setVerticalGroup(
            caseweekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        tabbedPane.addTab("CaseWeek", caseweekPanel);

        jScrollPane1.setViewportView(workshopsTable);

        workshopLabel.setText("Edit Workshop");

        workshopNameField.setColumns(20);

        workshopAddButton.setText("Add");
        workshopAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        workshopRoomTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        workshopDateField.setColumns(20);
        workshopDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workshopDateFieldActionPerformed(evt);
            }
        });

        workshopNameLabel.setLabelFor(workshopNameField);
        workshopNameLabel.setText("Name");

        workshopDateLabel.setLabelFor(workshopDateField);
        workshopDateLabel.setText("Date");

        workshopRoomTypeLabel.setLabelFor(workshopRoomTypeCombo);
        workshopRoomTypeLabel.setText("Room Type");

        workshopOrganizerLabel.setLabelFor(workshopOrganizerField);
        workshopOrganizerLabel.setText("Organizer");

        workshopOrganizerField.setColumns(20);
        workshopOrganizerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workshopOrganizerFieldActionPerformed(evt);
            }
        });

        workshopGroupQtyLabel.setLabelFor(workshopGroupQtyField);
        workshopGroupQtyLabel.setText("Group Quantity");

        workshopRoomSettingLabel.setLabelFor(workshopRoomSettingCombo);
        workshopRoomSettingLabel.setText("Room Setting");

        workshopGroupQtyField.setColumns(20);

        workshopRoomSettingCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        workshopRoomSettingCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workshopRoomSettingComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout workshopsPanelLayout = new javax.swing.GroupLayout(workshopsPanel);
        workshopsPanel.setLayout(workshopsPanelLayout);
        workshopsPanelLayout.setHorizontalGroup(
            workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workshopsPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(workshopsPanelLayout.createSequentialGroup()
                        .addGroup(workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(workshopsPanelLayout.createSequentialGroup()
                                .addGroup(workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(workshopNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(workshopAddButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(workshopDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(workshopRoomTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(workshopOrganizerLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(workshopGroupQtyLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(workshopRoomSettingLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(48, 48, 48)
                                .addGroup(workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(workshopDateField)
                                    .addComponent(workshopOrganizerField)
                                    .addComponent(workshopGroupQtyField)
                                    .addComponent(workshopNameField)
                                    .addComponent(workshopRoomSettingCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(workshopRoomTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(workshopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        workshopsPanelLayout.setVerticalGroup(
            workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workshopsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workshopsPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(workshopLabel)
                        .addGap(29, 29, 29)
                        .addGroup(workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workshopNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(workshopNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workshopDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(workshopDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workshopOrganizerLabel)
                            .addComponent(workshopOrganizerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workshopGroupQtyLabel)
                            .addComponent(workshopGroupQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workshopRoomSettingLabel)
                            .addComponent(workshopRoomSettingCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(workshopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workshopRoomTypeLabel)
                            .addComponent(workshopRoomTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(workshopAddButton)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(workshopsPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                        .addGap(61, 61, 61))))
        );

        tabbedPane.addTab("Workshops", workshopsPanel);

        javax.swing.GroupLayout speakersPanelLayout = new javax.swing.GroupLayout(speakersPanel);
        speakersPanel.setLayout(speakersPanelLayout);
        speakersPanelLayout.setHorizontalGroup(
            speakersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        speakersPanelLayout.setVerticalGroup(
            speakersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Speakers", speakersPanel);

        javax.swing.GroupLayout studentsPanelLayout = new javax.swing.GroupLayout(studentsPanel);
        studentsPanel.setLayout(studentsPanelLayout);
        studentsPanelLayout.setHorizontalGroup(
            studentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        studentsPanelLayout.setVerticalGroup(
            studentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Students", studentsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workshopOrganizerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workshopOrganizerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workshopOrganizerFieldActionPerformed

    private void workshopDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workshopDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workshopDateFieldActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        String name = workshopNameField.getText();
        String date = workshopDateField.getText();
        String groupQty = workshopGroupQtyField.getText();
        String roomSetting = (String)workshopRoomSettingCombo.getSelectedItem(); // toString()
        String organizer = workshopOrganizerField.getText();
        String roomType = workshopRoomTypeCombo.getSelectedItem().toString();
        // TODO call from another thread + UI update from the Swing's main thread
        try {
            dbActions.addWorkshop(name, date, groupQty, roomSetting, organizer, roomType);
        } catch (java.sql.SQLException ex) {
            setErrorMessage("workshops", ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_AddActionPerformed

    private void workshopRoomSettingComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workshopRoomSettingComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workshopRoomSettingComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseGUI().setVisible(true);
            }
        });
    }
    
    public void setErrorMessage(String tabName, String message) {
        //if (tabName.equalsIgnoreCase("caseweek")) {
            errorMessageLabel.setForeground(Color.RED);
            errorMessageLabel.setText(message);
        //}
    }
    
    public void setTableModel(String tabName, javax.swing.table.TableModel tableModel) {
        //if (tabName.equalsIgnoreCase("caseweek")) {
            workshopsTable.setModel(tableModel);
        //}
    }
    
    
    
    static class TabInfo {
        String tabName;
        boolean initialized;
        //javax.swing.JTable tableRef;
        
        public TabInfo(String tabName/*, javax.swing.JTable table*/) {
            this.tabName = tabName;
            //this.tableRef = table;
            this.initialized = false;
        }
    }
    
    private Map<Integer, TabInfo> tabs;   
    private DBActions dbActions;
    
    private Map<String, Integer> roomSettings;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel caseweekPanel;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel speakersPanel;
    private javax.swing.JPanel studentsPanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JButton workshopAddButton;
    private javax.swing.JTextField workshopDateField;
    private javax.swing.JLabel workshopDateLabel;
    private javax.swing.JTextField workshopGroupQtyField;
    private javax.swing.JLabel workshopGroupQtyLabel;
    private javax.swing.JLabel workshopLabel;
    private javax.swing.JTextField workshopNameField;
    private javax.swing.JLabel workshopNameLabel;
    private javax.swing.JTextField workshopOrganizerField;
    private javax.swing.JLabel workshopOrganizerLabel;
    private javax.swing.JComboBox<String> workshopRoomSettingCombo;
    private javax.swing.JLabel workshopRoomSettingLabel;
    private javax.swing.JComboBox<String> workshopRoomTypeCombo;
    private javax.swing.JLabel workshopRoomTypeLabel;
    private javax.swing.JPanel workshopsPanel;
    private javax.swing.JTable workshopsTable;
    // End of variables declaration//GEN-END:variables
}