CREATE OR REPLACE TRIGGER PERSONS_AUTONR
  BEFORE INSERT ON PERSONS
  FOR EACH ROW
BEGIN
  :new.P_id := PERSONS_SEQ.NEXTVAL;
END PERSONS_AUTONR;

-- For older versions of Oracle DBMS:
/*
CREATE OR REPLACE TRIGGER PERSONS_AUTONUMBER
  BEFORE INSERT ON PERSONS
  FOR EACH ROW
BEGIN
  SELECT PERSONS_SEQ.NEXTVAL
  INTO :new.P_id
  FROM DUAL;
END;
*/
